FROM ubuntu:22.04

RUN apt update && apt install -y \
    iproute2 \
    iputils-ping \
    net-tools \
    curl \
    vim \
    apache2 \
    tcpdump \
    isc-dhcp-client \
    telnet \
    netcat \
    sudo \
    systemctl


RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf


CMD ["bash"]
